### PR TITLE
Pull in fix to ptime_gettime_elapsed_us from portable_time project.

### LINKED ISSUE #40: Bug in elapsed time calculation
There is a bug in either the microsecond versions of the ptime routines or in the way that they are used by the sensor-polling threads in the odroid, odroid-ioctl, osp, wattsup and zcu102 implementations.  I can't tell which is incorrect because the function descriptions in common/ptime/ptime.h are a bit vague.  Specifically, they don't say what the units are for the `since` argument in any of the routines.  Right now, both the `_ns` and `_us` versions of the routines treat `since` as if it is in nanoseconds.  However, the polling routines capture an initial time in microseconds and then pass that to `energymon_gettime_elapsed_us` which passes it to `ptime_gettime_elapsed_us`.  Thus the first elapsed time calculation is incorrect and therefore the first energy calculation is incorrect.  The elapsed time routines update `since` with a time in nanoseconds so it works correctly for subsequent invocations and the difference between two energy readings will be correct but the total is not.

You can see this problem by running the interval_test.  Here's the output on a zcu102 compiled with ENERGYMON_DEBUG=1:
```
jasonm@ubuntu:~/energymon_github/_build64$ test/interval-test 100000
Initializing reading from ZCU102 INA226 Power Sensors
zcu102_poll_sensors: Read total power: 3025000 uW (3.025000 W)
zcu102_poll_sensors: Calculated energy: 3.025000 W * 6200404583720 us = 18756223865753 uJ
zcu102_poll_sensors: Read total power: 3025000 uW (3.025000 W)
zcu102_poll_sensors: Calculated energy: 3.025000 W * 7159 us = 21655 uJ
zcu102_poll_sensors: Read total power: 3025000 uW (3.025000 W)
zcu102_poll_sensors: Calculated energy: 3.025000 W * 35018 us = 105929 uJ
zcu102_poll_sensors: Read total power: 3000000 uW (3.000000 W)
zcu102_poll_sensors: Calculated energy: 3.000000 W * 7188 us = 21564 uJ
Start energy: 0 uJ   End energy: 18756224014901 uJ
Total energy: 18756224014901 uJ
Average power: 187562240.149010 W
Finished reading from ZCU102 INA226 Power Sensors
```

I'm happy to fix this if I can get clarification on whether the `since` argument for `energymon_gettime_elapsed_us` and `ptime_gettime_elapsed_us` is supposed to be in microseconds or nanoseconds.

### PR DESCRIPTION
**Pull request by jasonm128**
Fixes #40 using updated ptime routines from https://github.com/connorimes/portable_time project.  Also clarifies the argument descriptions in energymon-time-util.h

### CODE REVIEW

**Comment by connorimes** [comment]
Thanks.  One required and two suggested changes.
Required: Need to add back in the `#pragma GCC visibility push(hidden)` and `#pragma GCC visibility pop` lines in `ptime.h` (they aren't in the version in `portable_time`, sorry about that).
Suggested: Update `energymon_gettime_elapsed_us` parameter in header and impl to be `since_us` like was changed in `ptime`.
Additional suggestion: Update your commit message to include "Fixes #40" - GitHub will then automatically close the issue when the commit is merged.

**Comment by jasonm128** [comment]
Would you prefer that I push a new commit or amend the previous one and force push?

**Comment by connorimes** [comment]
Rebasing is ok for PRs but not required if you're uncomfortable with it.

**Comment by jasonm128** [comment]
FYI, it looks like including a reference to an issue in the PR is enough to close it automatically but I'll put it in the commit message anyway: https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by connorimes** [comment]
Merged! Thanks for putting up with the process.

**Pull request merged**
